# Generated by Django 5.2.9 on 2026-01-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_announcement_category_announcement_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='NotificationStaffs',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
    ]
